# Generated by Django 4.2.5 on 2024-12-18 16:16

from django.db import migrations, models
import luckyui.contrib.db.models.fields.char_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', luckyui.contrib.db.models.fields.char_field.CharField(max_length=150, verbose_name='char field')),
            ],
            options={
                'verbose_name': 'DB组件',
                'verbose_name_plural': 'DB组件',
            },
        ),
    ]
