# Generated by Django 4.2.5 on 2024-12-23 02:59

from django.db import migrations
import luckyui.contrib.db.models.fields.boolean_field
import luckyui.contrib.db.models.fields.char_field
import luckyui.contrib.db.models.fields.interger_field


class Migration(migrations.Migration):

    dependencies = [
        ('test_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodelfields',
            name='integer_field',
            field=luckyui.contrib.db.models.fields.interger_field.IntegerField(default=0, help_text='嘎嘞', verbose_name='integer field'),
        ),
        migrations.AddField(
            model_name='testmodelfields',
            name='switch_field',
            field=luckyui.contrib.db.models.fields.boolean_field.BooleanField(default=False, help_text='嘎嘞', verbose_name='switch field'),
        ),
        migrations.AlterField(
            model_name='testmodelfields',
            name='char_field',
            field=luckyui.contrib.db.models.fields.char_field.CharField(help_text='嘎嘞', max_length=150, verbose_name='char field'),
        ),
    ]
