# Generated by Django 4.2.5 on 2024-12-23 07:06

from django.db import migrations
import luckyui.contrib.db.models.fields.date_field
import luckyui.contrib.db.models.fields.date_time_field


class Migration(migrations.Migration):

    dependencies = [
        ('test_demo', '0002_testmodelfields_integer_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodelfields',
            name='date_field',
            field=luckyui.contrib.db.models.fields.date_field.DateField(default='2024-12-23', help_text='嘎嘞', verbose_name='date field'),
        ),
        migrations.AddField(
            model_name='testmodelfields',
            name='date_time_field',
            field=luckyui.contrib.db.models.fields.date_time_field.DateTimeField(default='2024-12-23 12:12:12', help_text='嘎嘞', verbose_name='date time field'),
        ),
    ]
