# Generated by Django 4.2.5 on 2025-01-03 08:31

from django.db import migrations
import luckyui.contrib.db.models.fields.interger_field


class Migration(migrations.Migration):

    dependencies = [
        ('test_demo', '0005_testspu_testsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodelfields',
            name='type_choice',
            field=luckyui.contrib.db.models.fields.interger_field.IntegerField(choices=[(0, 'test 1'), (1, 'test 2'), (2, 'test 3')], default=0, verbose_name='type choice field'),
        ),
    ]
