# Generated by Django 4.2.5 on 2025-01-05 04:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_demo', '0007_testmodelfields_money_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspu',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=10000, verbose_name='商品详情'),
        ),
    ]
